language: node_js
node_js:
  - "13"
before_install:
  # - sudo apt-get update
  # - sudo apt-get -y install pigpio
  # Manually install 'pigpio'
  - rm -f master.zip
  - sudo rm -rf pigpio-master
  - wget https://github.com/joan2937/pigpio/archive/master.zip
  - unzip master.zip
  - cd pigpio-master
  - make
  - sudo make install
